language: php

sudo: false

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - source .travis/travis.sh
  - xdebug-disable
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest;

script:
  - run-tests
